--PASSAR O CODIGO DA EDITORA E RECEBE O NOME DA EDITORA NO RETURN;
CREATE OR REPLACE FUNCTION nomeEditora(codigoEditora IN NUMBER) RETURN VARCHAR2
IS
    valorNome EDITORA.NOME%TYPE;
BEGIN

    SELECT NOME INTO valorNome
    FROM EDITORA
    WHERE CODEDITORA = CODIGOEDITORA;
    RETURN valorNome;

    EXCEPTION WHEN
        NO_DATA_FOUND THEN valorNome := 'Editora não cadastrada!';
    RETURN valorNome;

END;

----------------------------------------------------

DECLARE
    v_nome EDITORA.NOME%TYPE;
BEGIN 
    v_nome := NOMEEDITORA(1);
    DBMS_OUTPUT.PUT_LINE('EDITORA: ' || v_nome);
END;

SELECT TITULO, CODLIVRO, NOMEEDITORA(CODEDITORA) FROM LIVRO;

-------------------------------------
-- PASSAR O CODIGO DO LIVRO E RETORNAR QUANTOS LIVROS FORAM VENDIDOS;
CREATE OR REPLACE FUNCTION F_TOTAL_LIVROS_VENDIDOS(CODIGOLIVRO IN NUMBER) RETURN NUMBER     
IS 
    LIVROSVENDIDOS VENDA.QUANTIDADE%TYPE;
BEGIN
    SELECT L.TITULO, SUM(V.QUANTIDADE) QUANTIDADE INTO LIVROSVENDIDOS
    FROM VENDA V 
    JOIN LIVRO L ON V.CODLIVRO = L.CODLIVRO 
    WHERE V.CODLIVRO = CODIGOLIVRO 
    GROUP BY L.TITULO;
    RETURN LIVROSVENDIDOS;
    EXCEPTION WHEN
        NO_DATA_FOUND THEN LIVROSVENDIDOS := NULL;
        RETURN LIVROSVENDIDOS;
        END;
------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE P_TOTAL_LIVROS_VENDIDOS(CODIGOLIVRO IN NUMBER, QTDLIVRO OUT NUMBER)
IS 
BEGIN
    SELECT 
        SUM(V.QUANTIDADE) INTO QTDLIVRO 
    FROM VENDA V WHERE V.CODLIVRO = CODIGOLIVRO;
        EXCEPTION WHEN
            NO_DATA_FOUND THEN QTDLCREATE OR REPLACE PROCEDURE P_TITULO_LIVRO(P_CODLIVRO IN NUMBER, P_TITULO OUT VARCHAR )
IS
BEGIN
    SELECT 
    TITULO INTO P_TITULO
    FROM LIVRO WHERE CODLIVRO = P_CODLIVRO;
EXCEPTION WHEN NO_DATA_FOUND THEN
    P_TITULO := 'NAO EXISTE LIVRO';
END;qIVRO := NULL;
    END;

--OUUUUUUUUUU

CREATE OR REPLACE PROCEDURE P_TOTAL_LIVROS_VENDIDOS(CODIGOLIVRO IN NUMBER)
IS 
    QTDLIVRO VENDA.QUANTIDADE%TYPE;
BEGIN
    SELECT 
    SUM(V.QUANTIDADE) INTO QTDLIVRO 
    FROM VENDA V WHERE V.CODLIVRO = CODIGOLIVRO;
	DBMS_OUTPUT.PUT_LINE('QUANTIDADE: ' || QTDLIVRO);
    EXCEPTION WHEN
        NO_DATA_FOUND THEN QTDLIVRO := NULL;
END;
--TESTANDO A PROCEDURE
DECLARE
	VQTD VENDA.QUANTIDADE%TYPE;
BEGIN
	P_TOTAL_LIVROS_VENDIDOS(1,VQTD);
	DBMS_OUTPUT.PUT_LINE('QUANTIDADE DE LIVROS: '|| VQTD);
END;

-- OU EXEC P_TOTAL_LIVROS_VENDIDOS(1)

----------------