--Exercicio 01:
CREATE OR REPLACE FUNCTION F_QTD_LIVROS_VENDIDOS(P_AUTOR IN VARCHAR2) RETURN VARCHAR2
IS
    V_QTDLIVRO VENDA.QUANTIDADE%TYPE;
BEGIN 
    SELECT 
    SUM(V.QUANTIDADE), 
    A.NOME 
    INTO V_QTDLIVRO
    FROM LIVRO_AUTORIA LA 
    JOIN VENDA V ON V.CODLIVRO = LA.CODLIVRO 
    JOIN AUTOR A ON LA.MATRICULA = A.MATRICULA
    WHERE A.NOME = P_AUTOR;
    RETURN V_QTDLIVRO;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        V.QUANTIDADE := NULL;
    END;

--Exercicio 02
CREATE OR REPLACE FUNCTION F_DATA_ULTIMA_COMPRA(P_CPF IN NUMBER) RETURN DATE
IS
    V_ULTIMADATA VENDA.DATAVENDA%TYPE;
BEGIN
    SELECT
    MAX(V.DATAVENDA) INTO V_ULTIMADATA
    FROM VENDA V WHERE V.CPF = P_CPF;
	RETURN V_ULTIMADATA;
    EXCEPTION WHEN NO_DATA_FOUND THEN
    V_ULTIMADATA := SYSDATE;
	RETURN V_ULTIMADATA;
    END;